CCTVMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('surveillance.urls')),
]

surveillance/urls.py
from django.urls import path

from surveillance import views as surveillance_views

app_name = 'surveillance'

"""Contains all the urls to access surveillance views."""

urlpatterns = [
    path('', surveillance_views.home, name="home_page"),
    path('cameras', surveillance_views.CameraListView.as_view(), name="camera_list_view"),
    path('cameras/<int:pk>', surveillance_views.CameraDetailsView.as_view(), name="camera_detail_view"),
    path('video_feed/<int:cid>', surveillance_views.video_feed, name="video_feed"),
    path('violence_video_feed/<int:cid>', surveillance_views.violence_video_feed, name="violence_video_feed"),
]

templates/base.html
{% load static %}
{% load bootstrap5 %}
{% bootstrap_javascript %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} Admin Surv UI | Dashboard {% endblock %}</title>


    <link rel="stylesheet" href="{% static 'surveillance/css/bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'surveillance/css/font-awesome.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{% static 'surveillance/css/ionicons.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'surveillance/css/AdminLTE.min.css' %}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{% static 'surveillance/css/_all-skins.min.css' %}">
    <!-- Morris chart -->
    <link rel="stylesheet" href="{% static 'surveillance/css/morris.css' %}">
    <!-- jvectormap -->
    <link rel="stylesheet" href="{% static 'surveillance/css/jquery-jvectormap.css' %}">
    <!-- Date Picker -->
    <link rel="stylesheet"
          href="{% static 'surveillance/css/bootstrap-datepicker.min.css' %}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{% static 'surveillance/css/daterangepicker.css' %}">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="{% static 'surveillance/css/bootstrap3-wysihtml5.min.css' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% block add_style %}  {% endblock %}
</head>

<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    <header class="main-header">
        <!-- Logo -->
        <a href="index2.html" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>U</b>I</span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>Admin</b>surveillance</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <!-- Messages: style can be found in dropdown.less-->

                    <!-- Notifications: style can be found in dropdown.less -->
                    <li class="dropdown notifications-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-bell-o"></i>
                            <span class="label label-warning">10</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">You have 10 notifications</li>
                            <li>
                                <!-- inner menu: contains the actual data -->

                                <!-- Tasks: style can be found in dropdown.less -->
                            <li class="dropdown tasks-menu">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-flag-o"></i>
                                    <span class="label label-danger">9</span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="header">You have 9 tasks</li>
                                    <li>
                                        <!-- inner menu: contains the actual data -->
                                        <ul class="menu">

                                            <!-- end task item -->

                                            <!-- end task item -->
                                            <li><!-- Task item --></li>

                                            <!-- end task item -->
                                            <li><!-- Task item --></li>

                                            <!-- end task item -->
                                        </ul>
                                    </li>

                                    <!-- User Account: style can be found in dropdown.less -->
                                    <li class="dropdown user user-menu">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">

                                            <span class="hidden-xs">Safat Hossain</span>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <!-- User image -->
                                            <li class="user-header">
                                                <img src="dist/img/user2-160x160.jpg" class="img-circle"
                                                     alt="User Image">

                                                <p>

                                                    <small></small>
                                                </p>
                                            </li>
                                            <!-- Menu Body -->


                                            <!-- Menu Footer-->

                                            <!-- Control Sidebar Toggle Button -->
                                            <li>
                                                <a href="#" data-toggle="control-sidebar"><i
                                                        class="fa fa-gears"></i></a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->

            <ul class="sidebar-menu" data-widget="tree">
                <li class="header">MAIN NAVIGATION</li>
                <li class="active treeview">
                    <a href="{% url 'surveillance:camera_list_view' %}">
                        <i class="fa fa-camera"> Camera </i>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="active"><a href="{% url 'surveillance:camera_list_view' %}"><i class="fa fa-circle-o"></i> All Camera </a></li>
                        {% for camera in object_list %}
                            <li class="active"><a href="{% url 'surveillance:camera_detail_view' camera.pk %}"><i class="fa fa-circle-o"></i> Camera {{ camera.pk }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Dashboard
                <small>Control panel</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Dashboard</li>
            </ol>
        </section>
        <p align="center">
            {% bootstrap_messages %}
            {% block content %}

            {% endblock %}
        </p>

    </div>

    <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>

    </form>
</div>
<!-- /.tab-pane -->
</div>

</body>
</aside>
<!-- /.control-sidebar -->
<!-- Add the sidebar's background. This div must be placed
     immediately after the control sidebar -->
<div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<!-- jQuery 3 -->
<script src="{% static 'surveillance/js/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'surveillance/js/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'surveillance/js/bootstrap.min.js' %}"></script>
<!-- Morris.js charts -->
<script src="{% static 'surveillance/js/raphael.min.js' %}"></script>
<script src="{% static 'surveillance/js/morris.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'surveillance/js/jquery.sparkline.min.js' %}"></script>
<!-- jvectormap -->
<script src="{% static 'surveillance/js/jquery-jvectormap-1.2.2.min.js' %}"></script>
<script src="{% static 'surveillance/js/jquery-jvectormap-world-mill-en.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'surveillance/js/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'surveillance/js/moment.min.js' %}"></script>
<script src="{% static 'surveillance/js/daterangepicker.js' %}"></script>
<!-- datepicker -->
<script src="{% static 'surveillance/js/bootstrap-datepicker.min.js' %}"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{% static 'surveillance/js/bootstrap3-wysihtml5.all.min.js' %}"></script>
<!-- Slimscroll -->
<script src="{% static 'surveillance/js/jquery.slimscroll.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'surveillance/js/fastclick.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'surveillance/js/adminlte.min.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'surveillance/js/dashboard.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'surveillance/js/demo.js' %}"></script>
<script src="{% static 'main.js' %}"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
    {#    <div>#}
    {#        <img src="{% url 'surveillance:video_feed' %}" height="400" width="720">#}
    {#    </div>#}

{#    <div align="center">#}
{#        <img src="{% url 'surveillance:violence_video_feed' 1 %}" height="400" width="720">#}
{#    </div>#}
    <a href="{% url 'surveillance:camera_list_view' %}">
                        <i class="fa fa-camera"></i> <span>Cameras</span>
                    </a>
{% endblock %}